// Generated by gencpp from file offboard_pkg/MultiArucoInfo.msg
// DO NOT EDIT!


#ifndef OFFBOARD_PKG_MESSAGE_MULTIARUCOINFO_H
#define OFFBOARD_PKG_MESSAGE_MULTIARUCOINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <offboard_pkg/ArucoInfo.h>

namespace offboard_pkg
{
template <class ContainerAllocator>
struct MultiArucoInfo_
{
  typedef MultiArucoInfo_<ContainerAllocator> Type;

  MultiArucoInfo_()
    : header()
    , num_arucos(0)
    , aruco_infos()  {
    }
  MultiArucoInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , num_arucos(0)
    , aruco_infos(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _num_arucos_type;
  _num_arucos_type num_arucos;

   typedef std::vector< ::offboard_pkg::ArucoInfo_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::offboard_pkg::ArucoInfo_<ContainerAllocator> >::other >  _aruco_infos_type;
  _aruco_infos_type aruco_infos;





  typedef boost::shared_ptr< ::offboard_pkg::MultiArucoInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::offboard_pkg::MultiArucoInfo_<ContainerAllocator> const> ConstPtr;

}; // struct MultiArucoInfo_

typedef ::offboard_pkg::MultiArucoInfo_<std::allocator<void> > MultiArucoInfo;

typedef boost::shared_ptr< ::offboard_pkg::MultiArucoInfo > MultiArucoInfoPtr;
typedef boost::shared_ptr< ::offboard_pkg::MultiArucoInfo const> MultiArucoInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::offboard_pkg::MultiArucoInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::offboard_pkg::MultiArucoInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::offboard_pkg::MultiArucoInfo_<ContainerAllocator1> & lhs, const ::offboard_pkg::MultiArucoInfo_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.num_arucos == rhs.num_arucos &&
    lhs.aruco_infos == rhs.aruco_infos;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::offboard_pkg::MultiArucoInfo_<ContainerAllocator1> & lhs, const ::offboard_pkg::MultiArucoInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace offboard_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::offboard_pkg::MultiArucoInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::offboard_pkg::MultiArucoInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::offboard_pkg::MultiArucoInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::offboard_pkg::MultiArucoInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::offboard_pkg::MultiArucoInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::offboard_pkg::MultiArucoInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::offboard_pkg::MultiArucoInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ed01e66cfe7218a97aff05b031ab2f44";
  }

  static const char* value(const ::offboard_pkg::MultiArucoInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xed01e66cfe7218a9ULL;
  static const uint64_t static_value2 = 0x7aff05b031ab2f44ULL;
};

template<class ContainerAllocator>
struct DataType< ::offboard_pkg::MultiArucoInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "offboard_pkg/MultiArucoInfo";
  }

  static const char* value(const ::offboard_pkg::MultiArucoInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::offboard_pkg::MultiArucoInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"## 检测到的aruco码数量\n"
"int32 num_arucos\n"
"\n"
"## 每个aruco码的检测结果\n"
"ArucoInfo[] aruco_infos\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: offboard_pkg/ArucoInfo\n"
"std_msgs/Header header\n"
"\n"
"## aruco编码\n"
"int32 aruco_num\n"
"\n"
"## 是否检测到目标\n"
"bool detected\n"
"\n"
"## 目标位置-全局坐标系-(x,y,z)\n"
"float32[3] position\n"
"\n"
"## 目标姿态-四元数-(qx,qy,qz,qw)\n"
"float32[4] orientation\n"
"\n"
"## 视线角度-相机系下-(右方x角度为正,下方y角度为正)\n"
"float32[2] sight_angle\n"
"\n"
;
  }

  static const char* value(const ::offboard_pkg::MultiArucoInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::offboard_pkg::MultiArucoInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.num_arucos);
      stream.next(m.aruco_infos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MultiArucoInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::offboard_pkg::MultiArucoInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::offboard_pkg::MultiArucoInfo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "num_arucos: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num_arucos);
    s << indent << "aruco_infos[]" << std::endl;
    for (size_t i = 0; i < v.aruco_infos.size(); ++i)
    {
      s << indent << "  aruco_infos[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::offboard_pkg::ArucoInfo_<ContainerAllocator> >::stream(s, indent + "    ", v.aruco_infos[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OFFBOARD_PKG_MESSAGE_MULTIARUCOINFO_H
